name = "LegendDataManagement"
uuid = "9feedd95-f0e0-423f-a8dc-de0970eae6b3"
version = "0.2.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
PropertyDicts = "f8a19df8-e894-5f55-a973-672c1158cbca"
PropertyFunctions = "09e99361-2bb8-48a2-a80f-de58f0739eb4"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"

[extensions]
LegendDataManagementSolidStateDetectorsExt = "SolidStateDetectors"

[compat]
Dates = "1"
Distributed = "1"
Glob = "1"
JSON = "0.21, 1"
LRUCache = "1.5"
Pkg = "1"
Printf = "1"
PropDicts = "0.2.2"
PropertyDicts = "0.2"
PropertyFunctions = "0.2"
Requires = "1"
SolidStateDetectors = "0.8, 0.9"
StructArrays = "0.4, 0.5, 0.6"
Unitful = "1"
julia = "1.9"

[extras]
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
