name = "LegendDataManagement"
uuid = "9feedd95-f0e0-423f-a8dc-de0970eae6b3"
version = "0.2.8"

[deps]
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MIMEs = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
PropertyDicts = "f8a19df8-e894-5f55-a973-672c1158cbca"
PropertyFunctions = "09e99361-2bb8-48a2-a80f-de58f0739eb4"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"

[extensions]
LegendDataManagementRecipesBaseExt = "RecipesBase"
LegendDataManagementSolidStateDetectorsExt = "SolidStateDetectors"

[compat]
ClusterManagers = "0.4.6"
Dates = "1"
Distributed = "1"
Format = "1"
Glob = "1"
IntervalSets = "0.6, 0.7"
JSON = "0.21, 1"
LRUCache = "1.5"
LinearAlgebra = "1"
MIMEs = "0.1"
Markdown = "1"
Measurements = "2"
Pkg = "1"
Printf = "1"
ProgressMeter = "1"
PropDicts = "0.2.4"
PropertyDicts = "0.2"
PropertyFunctions = "0.2.1"
RecipesBase = "1"
SolidStateDetectors = "0.8, 0.9"
StaticStrings = "0.2"
StructArrays = "0.4, 0.5, 0.6"
Tables = "0.2, 1.0"
ThreadPinning = "0.7"
TypedTables = "1.4"
UUIDs = "1"
Unitful = "1"
julia = "1.9"
