name = "LegendDataManagement"
uuid = "9feedd95-f0e0-423f-a8dc-de0970eae6b3"
version = "0.4.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MIMEs = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
PropertyDicts = "f8a19df8-e894-5f55-a973-672c1158cbca"
PropertyFunctions = "09e99361-2bb8-48a2-a80f-de58f0739eb4"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"

[extensions]
LegendDataManagementLegendHDF5IOExt = ["LegendHDF5IO", "LegendDataTypes"]
LegendDataManagementPlotsExt = ["RecipesBase", "Plots"]
LegendDataManagementSolidStateDetectorsExt = "SolidStateDetectors"

[compat]
Dates = "<0.0.1, 1"
Distributed = "<0.0.1, 1"
Format = "1.2"
Glob = "1.3"
IntervalSets = "0.6, 0.7"
JSON = "0.21.2, 1"
LRUCache = "1.5"
LegendDataTypes = "0.1.13"
LegendHDF5IO = "0.1.14"
LinearAlgebra = "<0.0.1, 1"
MIMEs = "0.1, 1"
Markdown = "<0.0.1, 1"
Measurements = "2.2.1"
OhMyThreads = "0.5, 0.6, 0.7"
Pkg = "1"
Plots = "<0.0.1, 1"
Printf = "<0.0.1, 1"
ProgressMeter = "1.5"
PropDicts = "0.2.4"
PropertyDicts = "0.2.1"
PropertyFunctions = "0.2.2"
RecipesBase = "1"
SolidStateDetectors = "0.10.2"
StaticStrings = "0.2"
Statistics = "<0.0.1, 1"
StructArrays = "0.6.6, 0.7"
Tables = "1.1"
TypedTables = "1.4"
UUIDs = "<0.0.1, 1"
Unitful = "1.11"
julia = "1.10"
